### ISSUE TITLE
Разработать мокап "Личный кабинет для физ.лица"

### ISSUE THREAD

**Issue by KarambaKG** [OpenWalletKG/OpenWallet#1]
**Предыстория:**
Нужен мокап шаблон личного кабинета, чтобы понять что мы будем делать и планировать.

**Задача:**
Разработать шаблон-мокап "Личный кабинет для физ.лица"
Создать мокап на gravit io и расшарить его для всех членов команды.

**Методы решения:**
Обсудить с командой как будет выглядеть наш мокап Личного кабинета для физ.лица

**Сценарий тестирования:**
1) Создать мокап.
2) Расшарить всей команде.
3) Обсудить недочеты мокапа.

**Comment by zmanlynx** [comment]
Создана структура для mockup на gravit.io. Расшарено между членами комманды

**Comment by KarambaKG** [comment]
Мокап сделан https://gravit.io/d/Ekz1hxZeUG/!/edit
Запланировано: 30 мин
Потрачено: 30 мин
