### ISSUE TITLE
Разработать шаблон-мокап "Мои платежные системы"

### ISSUE THREAD

**Issue by KarambaKG** [OpenWalletKG/OpenWallet#10]
**Предыстория:**
Нужен шаблон-мокап, чтобы понять что мы будем делать и планировать.

**Задача:**
Разработать мокап "Мои платежные системы"
Создать мокап на gravit io и расшарить его для всех членов команды.

**Методы решения:**
Обсудить с командой как будет выглядеть наш мокап Личного кабинета для физ.лица

**Сценарий тестирования:**
1) Создать мокап.
2) Расшарить всей команде.
3) Обсудить недочеты мокапа.

**Comment by evgeniikotliarov** [comment]
Запланировано 1 час
Потрачено 1 час
https://gravit.io/d/4JW1b7-eLf/!/edit
