### ISSUE TITLE
Создать вьюшку "Главная страница"

### ISSUE THREAD

**Issue by KarambaKG** [OpenWalletKG/OpenWallet#15]
**Предыстория:**
Нужна главная страница. Лицо нашего проекта.

**Задача:**
Создать страницу "Главная" на примере мокапа https://gravit.io/d/4yM4Cvn0Sz/!/edit

**Методы решения:**
bootstrap

**Критерий готовности**
1) Создать страницу
2) Сравнить ее с мокапом.
3) Если похожа закрываем тикет.

**Comment by Daniiar** [comment]
Запланированное время: 3 часа
Потраченное время:
