### ISSUE TITLE
Cоздать удобночитаемые маршруты для регистрации и базовых операций с кошельком

### ISSUE THREAD

**Issue by vasview** [OpenWalletKG/OpenWallet#28]
**Предыстория:**
Нам нужно, чтобы в адресной строке браузера пользователя были понятные и осмысленные пути. 

**Задача:**
Создать маршруты в файле routes.rb. 
Переопределить нужные нам маршруты Devise. 
Проанализировать какие появяться контроллеры и методы в них. 
Понять как можно сгруппировать маршруты.

**Comment by vasview** [comment]
По-моему, есть необходимость создать CRUD, или почти CRUD без удаления для всех операция с кошельком, т.к. нам нужно будет предоставлять клиенту возможность проверки операции перед ее окончательным выполнением.

**Comment by KarambaKG** [comment]
Начальные роуты созданы.
