### ISSUE TITLE
Создать и спроектировать мокапы на регистрацию юридического и физического лица

### ISSUE THREAD

**Issue by Daniiar** [OpenWalletKG/OpenWallet#4]
**Предыстория:** 
Всей командой решено спроектировать мокапы на регистрацию юридического и физического лица.

**Задача:** 
1. Сделать главную страницу с кнопками регистрации и авторизации
2. Заполнить главную страницу любой информацией(чтобы не была пустой)
3. При регистрации обеспечить выбор между физическим и юридическим лицом
4. В регистрации любого лица разработать шаги регистрации на свое усмотрение
(например: https://start.webmoney.ru/)

**Методы решения:**
По предложению Дмитрия необходимо всем зарегистрироваться на gravit.io, попросить Дмитрия открыть доступ к мокапам, где будут хранится и редактироваться все мокапы

**Сценарий тестирования:**
1) Создать мокап
2) Открыть доступ на гравит ио
3) Обсудить мокап с командой

Планируемое время: 3 часа
Потраченное время: 2 часа

**Критерий готовности: Выполнено (100%)**

**Comment by evgeniikotliarov** [comment]
https://gravit.io/workspace/folder/VJZEgO2Crz
