### ISSUE TITLE
Вставить ссылку для лицензионного соглашения при регистрации

### ISSUE THREAD

**Issue by Daniiar** [OpenWalletKG/OpenWallet#44]
**Предыстория:** По мокапам не хватает лицензионного соглашения для юридического и физического лица
**Задача:** Вставить ссылку при регистрации на второй шаг, чтобы прочитать лицензионное соглашение
**Методы решения:**
**Сценарий тестирования:**
1. Заполнить поля первого и второго шага регистрации
2. Увидеть ссылку лицензионного соглашения
3. Перейти по ссылке лицензионного соглашения(должно открыться в новой вкладке)
4. Просмотреть лицензионное соглашение(в формате pdf)

**Comment by Daniiar** [comment]
Запланированное время: 2 часа
Потраченное время:

**Comment by KarambaKG** [comment]
Выполнено
