### ISSUE TITLE
Разработать мокап "Форма логина"

### ISSUE THREAD

**Issue by KarambaKG** [OpenWalletKG/OpenWallet#5]
**Предыстория:**
Нужен мокап, чтобы понять что мы будем делать и планировать.

**Задача:**
Разработать мокап "Форма логина"
Создать мокап на gravit io и расшарить его для всех членов команды.

**Методы решения:**
Обсудить с командой как будет выглядеть наш мокап "Форма логина"

**Сценарий тестирования:**
1) Создать мокап.
2) Расшарить всей команде.
3) Обсудить недочеты мокапа.

**Comment by Daniiar** [comment]
Time planned: 2 hours
Time spent:
