### ISSUE TITLE
Разработать мокап элемента Покупка-Продажа (Личный Кабинет)

### ISSUE THREAD

**Issue by zmanlynx** [OpenWalletKG/OpenWallet#6]
**Предыстория:**
Используя мокап-шаблон Личного кабинета создать мокап элемента Покупка-Продажа

**Задача:**
Разработать мокап элемента Личного кабината - Покупка/Продажа на gravit.io

**Методы решения**

**Сценарий тестирования:**
1) Создать мокап.
2) Расшарить всей команде.
3) Обсудить недочеты мокапа.

Планируемое время: 2 часа
Потраченное время:

**Критерий готовности: Выполнено 100%**

**Comment by AzamatJumabekov** [comment]
Потраченное время: 2 часа
