### ISSUE TITLE
Разработать шаблон-мокап "Мои счета"

### ISSUE THREAD

**Issue by KarambaKG** [OpenWalletKG/OpenWallet#7]
**Предыстория:**
Нужен мокап шаблон личного кабинета, чтобы понять что мы будем делать и планировать.

**Задача:**
Разработать шаблон-мокап "Мои счета"
Создать мокап на gravit io и расшарить его для всех членов команды.

**Методы решения:**
Обсудить с командой как будет выглядеть наш мокап Личного кабинета для физ.лица

**Сценарий тестирования:**
1) Создать мокап.
2) Расшарить всей команде.
3) Обсудить недочеты мокапа.

**Comment by Omkasokuluk** [comment]
Запланировано: 30 мин
Потрачено: 30 мин
