### ISSUE TITLE
Разработать шаблон-мокап "Оплата" 

### ISSUE THREAD

**Issue by KarambaKG** [OpenWalletKG/OpenWallet#8]
**Предыстория:**
Нужен шаблон-мокап, чтобы понять что мы будем делать и планировать.

**Задача:**
Разработать мокап "Оплата"
Создать мокап на gravit io и расшарить его для всех членов команды.

**Методы решения:**
Обсудить с командой как будет выглядеть наш мокап Личного кабинета для физ.лица

**Сценарий тестирования:**
1) Создать мокап.
2) Расшарить всей команде.
3) Обсудить недочеты мокапа.

**Comment by Daniiar** [comment]
Запланированное время: 2 часа
Потраченное время:

**Comment by evgeniikotliarov** [comment]
Так же форма создания платежа.
Запланировано 1 час.
Потрачено 1 час.
https://gravit.io/d/4J7zkxUeUf/!/edit

**Comment by KarambaKG** [comment]
Выполнили
